# Generated by Django 5.2.1 on 2025-05-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL slug')),
                ('article_type', models.CharField(choices=[('news', 'Новина'), ('task', 'Завдання')], default='news', max_length=10, verbose_name='Тип статті')),
                ('description', models.TextField(blank=True, help_text='Короткий опис для списку статей. Підтримує HTML-теги.', null=True, verbose_name='Короткий опис')),
                ('summary', models.TextField(blank=True, help_text='Підсумковий текст наприкінці статті. Підтримує HTML-теги.', verbose_name='Підсумок')),
                ('published_at', models.DateTimeField(verbose_name='Дата публікації')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендована стаття')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='Головне зображення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секції')),
                ('content', models.TextField(blank=True, help_text='Підтримує HTML-теги.', verbose_name='Текстовий вміст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Зображення')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис до зображення')),
                ('code', models.TextField(blank=True, verbose_name='Код')),
                ('language', models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('jsx', 'React'), ('sql', 'SQL'), ('python', 'Python')], default='javascript', max_length=20, verbose_name='Мова програмування')),
                ('code_description', models.TextField(blank=True, verbose_name='Опис коду')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='articles.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Секція статті',
                'verbose_name_plural': 'Секції статей',
                'ordering': ['order'],
            },
        ),
    ]
