# Generated by Django 5.2 on 2025-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_userprogress_delete_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тести'},
        ),
        migrations.AddField(
            model_name='test',
            name='color',
            field=models.CharField(choices=[('text-orange-500', 'Orange'), ('text-blue-500', 'Blue'), ('text-yellow-400', 'Yellow'), ('text-blue-400', 'Light Blue'), ('text-blue-600', 'Dark Blue'), ('text-green-500', 'Green'), ('text-purple-500', 'Purple'), ('text-red-500', 'Red'), ('text-gray-500', 'Gray')], default='text-gray-500', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='icon',
            field=models.CharField(choices=[('DiHtml5', 'HTML5'), ('DiCss3', 'CSS3'), ('DiJsBadge', 'JavaScript'), ('DiReact', 'React'), ('DiDatabase', 'Database/SQL'), ('DiDjango', 'Django')], default='DiJsBadge', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.IntegerField(default=30),
        ),
    ]
