# Generated by Django 5.2 on 2025-04-22 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_question_code_remove_question_hint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_code', models.TextField(help_text='Початковий код завдання')),
                ('task_type', models.CharField(choices=[('complete', 'Дописати код'), ('fill_gap', 'Заповнити пропуск'), ('fix_bug', 'Виправити помилку')], default='complete', max_length=20)),
                ('difficulty', models.IntegerField(default=1, help_text='Рівень складності від 1 до 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_tasks', to='core.test')),
            ],
            options={
                'verbose_name': 'Інтерактивне завдання',
                'verbose_name_plural': 'Інтерактивні завдання',
                'ordering': ['test', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.interactivetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спроба інтерактивного завдання',
                'verbose_name_plural': 'Спроби інтерактивних завдань',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.TextField(help_text='Правильний варіант рішення')),
                ('is_primary', models.BooleanField(default=False, help_text='Чи це основне рішення')),
                ('hint', models.TextField(blank=True, help_text='Підказка для цього рішення', null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.interactivetask')),
            ],
            options={
                'verbose_name': 'Рішення завдання',
                'verbose_name_plural': 'Рішення завдань',
            },
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_progress', to='core.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогрес інтерактивних завдань',
                'verbose_name_plural': 'Прогрес інтерактивних завдань',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
