# Generated by Django 5.2 on 2025-04-27 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interactivetask_taskattempt_tasksolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField(verbose_name='Вміст статті')),
                ('summary', models.TextField(help_text='Короткий опис для списку статей', verbose_name='Короткий опис')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендована стаття')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='Головне зображення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис')),
                ('position', models.CharField(choices=[('top', 'Верх статті'), ('middle', 'Середина статті'), ('bottom', 'Низ статті')], default='middle', max_length=10, verbose_name='Позиція')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Зображення статті',
                'verbose_name_plural': 'Зображення статей',
                'ordering': ['position', 'order'],
            },
        ),
    ]
