# Generated by Django 5.2 on 2025-04-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_article_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views_count',
        ),
        migrations.CreateModel(
            name='ArticleCodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('jsx', 'React JSX'), ('java', 'Java'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('sql', 'SQL'), ('bash', 'Bash/Shell'), ('typescript', 'TypeScript'), ('json', 'JSON'), ('xml', 'XML')], default='javascript', max_length=20, verbose_name='Мова програмування')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('position', models.CharField(choices=[('top', 'Верх статті'), ('middle', 'Середина статті'), ('bottom', 'Низ статті')], default='middle', max_length=10, verbose_name='Позиція')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='core.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Код статті',
                'verbose_name_plural': 'Коди статей',
                'ordering': ['position', 'order'],
            },
        ),
    ]
