# Generated by Django 5.2 on 2025-04-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_article_views_count_articlecodesnippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news', 'Новина'), ('task', 'Завдання')], default='news', max_length=10, verbose_name='Тип статті'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Короткий опис для списку статей', null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Підсумковий текст наприкінці статті', verbose_name='Підсумок'),
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення'), ('code', 'Код')], max_length=10, verbose_name='Тип секції')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок відображення')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок секції')),
                ('content', models.TextField(blank=True, verbose_name='Текстовий вміст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Зображення')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис до зображення')),
                ('code', models.TextField(blank=True, verbose_name='Код')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='Мова програмування')),
                ('code_description', models.TextField(blank=True, verbose_name='Опис коду')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Секція статті',
                'verbose_name_plural': 'Секції статей',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ArticleCodeSnippet',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
