# Generated by Django 5.2 on 2025-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_articleimage_article_remove_article_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at'], 'verbose_name': 'Питання для тестів', 'verbose_name_plural': 'Питання для тестів'},
        ),
        migrations.RemoveField(
            model_name='articlesection',
            name='section_type',
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='language',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('jsx', 'React'), ('sql', 'SQL'), ('python', 'Python')], default='javascript', max_length=20, verbose_name='Мова програмування'),
        ),
    ]
