# Generated by Django 5.2 on 2025-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Короткий опис для списку статей. Підтримує HTML-теги. Використовуйте <strong>текст</strong> для виділення жирним.', null=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Підсумковий текст наприкінці статті. Підтримує HTML-теги. Використовуйте <strong>текст</strong> для виділення жирним.', verbose_name='Підсумок'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='content',
            field=models.TextField(blank=True, help_text='Підтримує HTML-теги. Використовуйте <strong>текст</strong> для виділення жирним.', verbose_name='Текстовий вміст'),
        ),
    ]
