# Generated by Django 5.2 on 2025-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprogress_options_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('youtube_id', models.CharField(max_length=20, verbose_name='ID відео на YouTube')),
                ('description', models.TextField(verbose_name='Опис')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('qa', 'QA'), ('other', 'Інше')], default='frontend', max_length=20, verbose_name='Категорія')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='junior', max_length=20, verbose_name='Рівень')),
                ('featured', models.BooleanField(default=False, verbose_name='Рекомендоване')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Відео співбесіди',
                'verbose_name_plural': 'Відео співбесід',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
