# Generated by Django 5.2.1 on 2025-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comment_code_comment_code_language_comment_has_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.CharField(choices=[('technical', 'Технічні питання'), ('interview', 'Питання до співбесід'), ('career', "Кар'єра"), ('other', 'Інше')], default='other', max_length=20, verbose_name='Категорія'),
        ),
    ]
