# Generated by Django 5.2.1 on 2025-05-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_forumtopic_category'),
    ]

    operations = [
    ]
