# Generated by Django 5.2.1 on 2025-05-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('initial_code', models.TextField(help_text='Початковий код завдання', verbose_name='Початковий код')),
                ('task_type', models.CharField(choices=[('complete', 'Дописати код'), ('fill_gap', 'Заповнити пропуск'), ('fix_bug', 'Виправити помилку')], default='complete', max_length=20, verbose_name='Тип завдання')),
                ('difficulty', models.IntegerField(default=1, help_text='Рівень складності від 1 до 5', verbose_name='Складність')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_tasks', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Інтерактивне завдання',
                'verbose_name_plural': 'Інтерактивні завдання',
                'ordering': ['test', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(verbose_name='Відправлений код')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершення')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tasks.interactivetask', verbose_name='Завдання')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Спроба інтерактивного завдання',
                'verbose_name_plural': 'Спроби інтерактивних завдань',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.TextField(help_text='Правильний варіант рішення', verbose_name='Код рішення')),
                ('is_primary', models.BooleanField(default=False, help_text='Чи це основне рішення', verbose_name='Основне рішення')),
                ('hint', models.TextField(blank=True, help_text='Підказка для цього рішення', null=True, verbose_name='Підказка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tasks.interactivetask', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Рішення завдання',
                'verbose_name_plural': 'Рішення завдань',
            },
        ),
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='Виконані завдання')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='Загальна кількість завдань')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_progress', to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прогрес інтерактивних завдань',
                'verbose_name_plural': 'Прогрес інтерактивних завдань',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
