# Generated by Django 5.2.1 on 2025-05-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('question', models.TextField(verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Питання для тестів',
                'verbose_name_plural': 'Питання для тестів',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('duration', models.IntegerField(verbose_name='Тривалість (хв)')),
                ('questions', models.IntegerField(default=30, verbose_name='Кількість питань')),
                ('icon', models.CharField(choices=[('DiHtml5', 'HTML5'), ('DiCss3', 'CSS3'), ('DiJsBadge', 'JavaScript'), ('DiReact', 'React'), ('DiDatabase', 'Database/SQL'), ('DiDjango', 'Django')], default='DiJsBadge', max_length=50, verbose_name='Іконка')),
                ('color', models.CharField(choices=[('text-orange-500', 'Orange'), ('text-blue-500', 'Blue'), ('text-yellow-400', 'Yellow'), ('text-blue-400', 'Light Blue'), ('text-blue-600', 'Dark Blue'), ('text-green-500', 'Green'), ('text-purple-500', 'Purple'), ('text-red-500', 'Red'), ('text-gray-500', 'Gray')], default='text-gray-500', max_length=50, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Результат (%)')),
                ('attempts', models.IntegerField(default=0, verbose_name='Кількість спроб')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Дата завершення')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прогрес тесту',
                'verbose_name_plural': 'Прогрес тестів',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Результат (%)')),
                ('correct_answers', models.IntegerField(verbose_name='Правильні відповіді')),
                ('total_questions', models.IntegerField(verbose_name='Загальна кількість питань')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершення')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_history', to='tests.userprogress', verbose_name='Прогрес')),
            ],
            options={
                'verbose_name': 'Спроба тесту',
                'verbose_name_plural': 'Спроби тестів',
                'ordering': ['-completed_at'],
            },
        ),
    ]
